### ISSUE TITLE
need to add localized script to functions.php

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/starfish-winter-2018#1]
A localized script is required to allow rest api requests to work on staging & local sites without hardcoding the get url.

e.g. add this to your functions.php

wp_localize_script( 'profile-popup', 'sf_vars', array(
	'rest_url'      => esc_url_raw( rest_url() ),
	'wpapi_nonce'   => wp_create_nonce( 'wp_rest' )
) );

notice that 'profile-popup' needs to match the other script you enqueued and rest_url is the variable we can use in our get request e.g. sf_vars.rest_url

https://github.com/redacademy/starfish-winter-2018/blob/5f68498cf270ff87675f0e37f23c21e94a21a482/themes/thestarfish/functions.php#L114

**Comment by PaulDudsdeemaytha** [comment]
added!
