### ISSUE TITLE
last item in nav being cut off

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/starfish-winter-2018#10]
Currently with the larger menu dropdown the last item in the list may sometimes be cut-off in the browser.

One fix you can try is to adjust the last element and move the sub menu over a bit e.g. something like...

 #site-navigation ul > li:last-of-type .sub-menu {
        transform: translate(-50%,0);
    }

Also note that you shouldn't use id's as selectors, the reason I did is because that's what's in your css right now, please try to refactor this to work without relying on using id selectors.

**Comment by PaulDudsdeemaytha** [comment]
no longer cut off
