### ISSUE TITLE
image alt tags

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/starfish-winter-2018#11]
It looks like most of the images in the theme are missing alt tags. 

Keep in mind that you should add these even if you don't have a description. 

If you want to hide img elements from the a11y tree you can use an empty alt tag e.g. alt=""

Otherwise you can try adding the alt tags with php

For reference you can see the W3C errors at: https://validator.w3.org/nu/?showsource=yes&showoutline=yes&doc=http%3A%2F%2Fstarfish.van.cp.academy.red%2Fabout%2F#l126c135

For more about how to get the alt text for CFS images please take a look at: http://wpandsuch.com/return-the-alt-tags-on-images-using-custom-field-suite/

**Comment by rcass** [comment]
Looks like the alt tags have been resolved 👌
