### ISSUE TITLE
css linked in <head> should be enqueued in functions.php

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/starfish-winter-2018#12]
https://github.com/redacademy/starfish-winter-2018/blob/e6eacfe601d12f86b2bcb1aca21642e404c96a90/themes/thestarfish/header.php#L13-L15

Please enqueue these styles in functions.php instead of hard-coding them in the <head>

**Comment by nikakey** [comment]
I solved this issue, could it be closed? I'm not sure who can close it...

**Comment by resonantdoghouse** [comment]
Sounds good, I'll close the issue now.
