### ISSUE TITLE
unnecessary code

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/starfish-winter-2018#15]
https://github.com/redacademy/starfish-winter-2018/blob/bd8da11dd58f84a2a847080f81b54f8420cb20f5/themes/thestarfish/team.php#L15-L21

You can remove this code from our template since it's not the blog index or home page.

In face you can probably remove the standard loop since the content is all coming in from CFS below

**Comment by PaulDudsdeemaytha** [comment]
Okay, got rid of the unnecessary PHP and html from that page

**Comment by rcass** [comment]
Hmm it still looks like that code is there on team.php 🤔 

https://github.com/redacademy/starfish-winter-2018/blob/3131df442177f3537433082af766b6e7323e2609/themes/thestarfish/team.php#L15-L21

**Comment by PaulDudsdeemaytha** [comment]
fixed!

**Comment by rcass** [comment]
Sweet I can see that it is removed 👍 

(Heads up, the indentation in that files is kinda crazy, please fix that 🙏
