### ISSUE TITLE
functions.php Organization

### ISSUE THREAD

**Issue by rcass** [redacademy/starfish-winter-2018#17]
To prevent the functions.php from getting to long, it would be best to add extra/additional functions to the files that are in the includes folder (`inc/`).

https://github.com/redacademy/starfish-winter-2018/blob/bd8da11dd58f84a2a847080f81b54f8420cb20f5/themes/thestarfish/functions.php#L135-L145

For the code above, just need to move it to `inc/extras.php`

Also wonder why this is needed?

**Comment by nikakey** [comment]
It's needed to take just the first string excerpt from the journal posts for the front-page carousel. On the journal page we need the paragraph excerpt.

**Comment by rcass** [comment]
Oh interesting... I would love to take a look a closer look at this tomorrow. Let's chat about it at tomorrows group check in

**Comment by nikakey** [comment]
Yeah, sure :)
